### ISSUE TITLE
Add additional Quebec csv data

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [jeanpaulrsoucy/covid-19-canada-gov-data#77]
https://www.quebec.ca/en/health/health-issues/a-z/2019-coronavirus/situation-coronavirus-in-quebec/
https://www.quebec.ca/sante/problemes-de-sante/a-z/coronavirus-2019/situation-coronavirus-quebec/

French and English versions of some files.

**Comment by jeanpaulrsoucy** [comment]
Wayback machine may have old versions of new data files --- I think the only ones I really care about are vaccine data files.

**Comment by mschoettle** [comment]
There is also a vaccine CSV file that might be interesting to you: https://cdn-contenu.quebec.ca/cdn-contenu/sante/documents/Problemes_de_sante/covid-19/csv/doses-vaccins-en.csv
